//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.19 at 05:08:49 PM IST 
//


package soap.invoices;

import javax.xml.bind.annotation.XmlRegistry;



@XmlRegistry
public class ObjectFactory {


    public ObjectFactory() {
    }


    public soap.invoices.GetInvoiceDetailsResponse createGetInvoiceDetailsResponse() {
        return new soap.invoices.GetInvoiceDetailsResponse();
    }


    public soap.invoices.InvoiceDetails createInvoiceDetails() {
        return new soap.invoices.InvoiceDetails();
    }


    public soap.invoices.GetInvoiceDetailsRequest createGetInvoiceDetailsRequest() {
        return new soap.invoices.GetInvoiceDetailsRequest();
    }

}
